name: Build and run tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ "main" ]

env:
  FIRESTORE_EMULATOR_HOST: localhost:8080
  FIRESTORE_PROJECT_ID: project-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Add Org Nuget Source
        run: dotnet nuget add source --username mihail-brinza --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/down-cast/index.json"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: .NET Tests                  # Name of the check run which will be created
          path: test/**/TestResults/test-results.trx    # Path to test results
          reporter: dotnet-trx              # Format of test results  
